### ISSUE TITLE
[Bug] Merging default settings does not work

### ISSUE THREAD

**Issue by lucianholt97** [glorand/laravel-model-settings#70] opened 2020-09-25 09:03 UTC
Settings are merged with default settings in the AbstractSettingsManager.

```
/**
     * @return array
     */
    public function all(): array
    {
        $array = [];
        foreach (array_merge($this->model->getDefaultSettings(), $this->model->getSettingsValue()) as $key => $value) {
            Arr::set($array, $key, $value);
        }
        return $array;
    }
```

The issue with this logic is that we are merging two completely different kinds of arrays. The default settings are (or should be) a flat array with dot notation whereas the getSettingsValue may return a deeply nested array from `json_decode`. Merging both will result in overwriting nested defaults with the current empty value (especially a problem when adding new nested settings).

There are two simple approaches to solve this issue.
1. Use nested arrays on both sides and use `array_merge_recursive` 
2. (Favorite) Flatten the settings value with dot notation before merging. Keep in mind that you cannot use Arr:dot for this purpose since it would also flatten non-associative arrays like `['array.0' => value]` which results in poor merging.

You can use this instead:
```
/**
     * Check if array is associative and not sequential
     * @param array $arr
     * @return bool
     */
    static function isAssoc(array $arr)
    {
        if (array() === $arr) return false;
        return array_keys($arr) !== range(0, count($arr) - 1);
    }

    /**
     * Flatten array with dots for settings package
     * @param $array
     * @param string $prepend
     * @return array
     */
    static function dotFlatten($array, $prepend = '') {
        $results = [];
        foreach ($array as $key => $value) {
            // only re-run if nested array is associative (key-based)
            if (is_array($value) && static::isAssoc($value) && !empty($value)) {
                $results = array_merge($results, static::dotFlatten($value, $prepend.$key.'.'));
            } else {
                $results[$prepend.$key] = $value;
            }
        }
        return $results;
    }
```

Thanks in advance!

**Comment by ametad** [comment] 2020-11-16 09:57
Hi @lucianholt97 ,

Nice work in tackling the problem: "especially a problem when adding new nested settings".

Something is not clear for me yet though, how do you propose to define the default settings in a model? 

I am used to set defaults like this (just an example):

```php

class User extends Model
{

    use HasSettingsField;

    public $defaultSettings = [
        'dashboard' => [
            'type' => 'extensive'
        ],
        'permissions' => [
            'documents' => true,
            'overviews' => true,
        ],
    ];
```

Are you suggesting this would be defined in so called 'dot notation'? What about a nested array as seen above?

**Comment by lucianholt97** [comment] 2020-11-16 23:39
@ametad interesting question. Actually, I prefer to define all possible setting keys in an enum with dot notation and then use the enum to define the defaults as flat array. This has the advantage that I can safely get specific nested setting via the get() method using the enum.  
But I guess the package should support both approaches.

```
class UserSettings extends Enum {
    const DASHBOARD_TYPE = 'dashboard.type';
}

class User extends Model
{

    use HasSettingsField;

    public $defaultSettings = [
       UserSettings::DASHBOARD_TYPE => 'extensive'
    ];

```

**Comment by ametad** [comment] 2020-11-17 10:19
Yeah, it seems to me also that both ways should work. Just checking! Thanks.

**Comment by ametad** [comment] 2020-11-17 10:26
BTW @lucianholt97 The `Enum` class you use, what is that? I do not know of such class in native PHP...

**Comment by TCURT15** [comment] 2020-11-25 13:54
I am also having an issue merging default settings. New settings in my config file are not merged with the settings already saved in the database. Need a fix ASAP.

**Comment by glorand** [comment] 2020-11-26 15:51
> I am also having an issue merging default settings. New settings defined in my config file are not merged with the settings already saved in the database. Need a fix ASAP.

Hello @TCURT15 

Can you describe your problem with a concrete example. Like code and data. 
Thanks!

**Comment by lucianholt97** [comment] 2020-11-26 18:25
@TCURT15 this is probably due to the cache all strategy. You need to either invalidate the cache when changing defaults or disable the cache all strategy via the env.
I understand that it might be confusion to have it enabled as default.

**Comment by lucianholt97** [comment] 2020-11-26 18:27
@ametad I am using the `bensampo/laravel-enum` package for enums. Should have loaded it in the code example 😉

**Comment by glorand** [comment] 2020-11-26 22:27
@lucianholt97 Let's say we have this default settings:

```php
$defaultSettings = [
            'dashboard' => [
                'type' => 'extensive'
            ],
            'permissions' => [
                'documents' => true,
                'overviews' => true,
            ],
        ];
```

and we save the following array as model setting:
```php
$settings = [
            'permissions' => [
                'documents' => false,
            ],
        ]
```
With your "flatten" solution the model setting will be:
```php
 [
            'dashboard' => [
                'type' => 'extensive'
            ],
            'permissions' => [
                'documents' => false,
                'overviews' => true,
            ],
        ];
```
As you can see the permissions.overviews still present in the settings but probably the user just want to delete it.

In this case the expected result for the settings I think need to be:
```php
[
            'dashboard' => [
                'type' => 'extensive'
            ],
            'permissions' => [
                'documents' => false
            ],
        ];
```

**Comment by lucianholt97** [comment] 2020-11-26 23:01
@glorand I understand your point here. It may be more of a general question whether you prefer a predictable schema for your settings or if you want to dynamically add and remove keys.  
Since I am using the settings for first-party stuff and don't let my user modify the schema it's much better to always have the same or minimum schema to rely on. Especially with nested options, you would always mess with optional chaining in the frontend before checking the essential value of a setting.  

Can you give an example when it's actually useful to modify the setting structure during runtime?

**Comment by glorand** [comment] 2020-11-26 23:30
You convinced me with the "predictable schema". Probably will split your PR in multiple parts, and will update also the test files.

**Comment by TCURT15** [comment] 2020-12-10 13:13
> > I am also having an issue merging default settings. New settings defined in my config file are not merged with the settings already saved in the database. Need a fix ASAP.
> 
> Hello @TCURT15
> 
> Can you describe your problem with a concrete example. Like code and data.
> Thanks!


I am using the HasSettingsTable trait on my Company model. I have the following default settings defined in model_settings

` 'call' => [
                'ftc_calling_hours' => true,
                'ftc_calling_hours_manual_override' => true,
            ],
`

Updating these settings works fine and I see the changes in the database. The issue is when I go back and add a new setting in model_settings, e.g.:

` 'call' => [
                'ftc_calling_hours' => true,
                'ftc_calling_hours_manual_override' => true,
               'call_recording_disabled' => false,
            ],
`

and then try to return the call settings for a company 

`Company::first()->settings()->get('call')`

`"ftc_calling_hours" => true,
     "ftc_calling_hours_manual_override" => false`

The new 'call_recording_disabled' setting is missing. I would assume it should be pulling from that config file and merging the settings with what I have in my database. I have tried clearing cache, disabling cache all together, and nothing seems to make it appear.

**Comment by glorand** [comment] 2020-12-10 13:48
@lucianholt97 and @TCURT15 please check the last version of the package

**Closed** 2021-04-07 20:16 UTC
